.\" Manpage for nemesis-pkg

.TH man 8 "13 Aug 2023" "0.1" "nemesis-pkg man page"
.SH NAME
nemesis-pkg \- Tiny Package Manager for Nemesis
.SH SYNOPSIS
nemesis-pkg [operation]
.SH DESCRIPTION
nemesis-pkg is a tiny and fast package manager for Project Nemesis..
.SH OPTIONS
[h]elp - Show help page
.br
[i]nstall - Install a package
.br
[l]ist - List packages and repos
.br
[L]og - View nemesis-pkg log
.br
[s]earch - Search packages present
.br
[S]ync - Sync package database
.br
[u]ninstall - Uninstall a package
.br
[U]pgrade - Upgrade packages
.SH SEE ALSO
kiss, pacman
.SH AUTHOR
Project Nemesis
